version: '3.4'
services:
  db:
    image: bbnsdevelop/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: bbnsdevelop/rest-with-spring-boot-udemy
    restart: always
    build: ./restFull_SpringBoot_Docker
    working_dir: /restFull_SpringBoot_Docker
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./restFull_SpringBoot_Docker/target:/restFull_SpringBoot_Docker
#      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
#    command: mvn clean spring-boot:run
    command: java -jar APISpringBootDocker-0.0.1-SNAPSHOT.jar
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge